# Generated by Django 4.2.5 on 2024-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share',
            field=models.ManyToManyField(to='locker.upload'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(max_length=100),
        ),
    ]
