# Generated by Django 4.2.5 on 2024-07-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_alter_profile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='dwnldprms',
            field=models.BooleanField(default=False),
        ),
    ]
