# Generated by Django 4.2.5 on 2024-07-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0005_share_dwnldprms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='dwnldprms',
        ),
    ]
