# Generated by Django 4.2.5 on 2024-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_remove_share_dwnldprms'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='dwnldperm',
            field=models.BooleanField(default=False),
        ),
    ]
