# Generated by Django 4.2.5 on 2024-07-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0007_share_dwnldperm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='dwnldperm',
            new_name='dwnldprms',
        ),
    ]
